<header style="text-align: center;">
    <h1 style="font-variant: small-caps; padding-bottom: .5em;">
        Trabalho 3 - Yuri Lopes e Maurício Júnior
    </h1>
</header>
<!-- Endliche Differenzmethode -->

In [2]:
# Fonte: http://scikit-learn.org/stable/auto_examples/classification/plot_digits_classification.html

# Standard scientific Python imports
import matplotlib.pyplot as plt

# Import datasets, classifiers and performance metrics
from sklearn import datasets, svm, metrics
from sklearn.metrics import accuracy_score

# The digits dataset
digits = datasets.load_digits()

# To apply a classifier on this data, we need to flatten the image, to
# turn the data in a (samples, feature) matrix:
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))

# Create a classifier: a support vector classifier
classifier = svm.SVC(gamma=0.001)

# We learn the digits on the first half of the digits
classifier.fit(data[:n_samples // 2], digits.target[:n_samples // 2])

# Now predict the value of the digit on the second half:
expected = digits.target[n_samples // 2:]
predicted = classifier.predict(data[n_samples // 2:])

accuracy = accuracy_score(predicted, expected)

print("SVM\n")

#print("Classification report for classifier %s:\n%s\n"
 #     % (classifier, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

print("\nAccuracy: %s" % accuracy)

SVM

Confusion matrix:
[[87  0  0  0  1  0  0  0  0  0]
 [ 0 88  1  0  0  0  0  0  1  1]
 [ 0  0 85  1  0  0  0  0  0  0]
 [ 0  0  0 79  0  3  0  4  5  0]
 [ 0  0  0  0 88  0  0  0  0  4]
 [ 0  0  0  0  0 88  1  0  0  2]
 [ 0  1  0  0  0  0 90  0  0  0]
 [ 0  0  0  0  0  1  0 88  0  0]
 [ 0  0  0  0  0  0  0  0 88  0]
 [ 0  0  0  1  0  1  0  0  0 90]]

Accuracy: 0.968854282536


In [5]:
# Fonte: http://scikit-learn.org/stable/auto_examples/classification/plot_digits_classification.html

# Standard scientific Python imports
import matplotlib.pyplot as plt

# Import datasets, classifiers and performance metrics
from sklearn import datasets, metrics
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# The digits dataset
digits = datasets.load_digits()

# To apply a classifier on this data, we need to flatten the image, to
# turn the data in a (samples, feature) matrix:
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))

# Create a classifier: a support vector classifier
classifier = MLPClassifier(solver='lbfgs', alpha=1e-5)

# We learn the digits on the first half of the digits
classifier.fit(data[:n_samples // 2], digits.target[:n_samples // 2])

# Now predict the value of the digit on the second half:
expected = digits.target[n_samples // 2:]
predicted = classifier.predict(data[n_samples // 2:])

accuracy = accuracy_score(predicted, expected)

print("Neural Network\n")

#print("Classification report for classifier %s:\n%s\n"
 #     % (classifier, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

print("\nAccuracy: %s" % accuracy)

Neural Network

Confusion matrix:
[[86  0  0  0  0  0  2  0  0  0]
 [ 0 84  0  1  0  0  0  0  0  6]
 [ 0  0 86  0  0  0  0  0  0  0]
 [ 0  0  3 79  0  4  0  0  5  0]
 [ 1  1  0  0 84  0  3  0  0  3]
 [ 0  0  1  1  0 84  2  0  0  3]
 [ 0  1  0  0  0  0 90  0  0  0]
 [ 0  0  2  0  0  0  0 84  0  3]
 [ 0  4  0  0  0  3  1  0 80  0]
 [ 2  0  0  1  0  2  0  3  0 84]]

Accuracy: 0.935483870968


In [4]:
# Fonte: http://scikit-learn.org/stable/auto_examples/classification/plot_digits_classification.html

# Standard scientific Python imports
import matplotlib.pyplot as plt

# Import datasets, classifiers and performance metrics
from sklearn import datasets, metrics
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# The digits dataset
digits = datasets.load_digits()

# To apply a classifier on this data, we need to flatten the image, to
# turn the data in a (samples, feature) matrix:
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))

# Create a classifier: a support vector classifier
classifier = MultinomialNB()

# We learn the digits on the first half of the digits
classifier.fit(data[:n_samples // 2], digits.target[:n_samples // 2])

# Now predict the value of the digit on the second half:
expected = digits.target[n_samples // 2:]
predicted = classifier.predict(data[n_samples // 2:])

accuracy = accuracy_score(predicted, expected)

print("Naive Bayes\n")

#print("Classification report for classifier %s:\n%s\n"
 #     % (classifier, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

print("\nAccuracy: %s" % accuracy)

Naive Bayes

Confusion matrix:
[[86  0  0  0  1  0  0  0  1  0]
 [ 0 60  8  0  2  1  0  0  9 11]
 [ 1  3 75  5  0  0  0  0  0  2]
 [ 0  0  1 76  0  2  0  4  6  2]
 [ 1  0  0  0 86  0  0  2  3  0]
 [ 0  0  0  0  1 64  2  0  0 24]
 [ 0  2  0  0  0  0 89  0  0  0]
 [ 0  0  2  0  4  2  0 80  1  0]
 [ 0  2  2  0  1  4  0  1 73  5]
 [ 0  0  0  3  0  3  0  3  2 81]]

Accuracy: 0.856507230256


### Discussão dos Resultados
O classificador SVM apresentou melhores resultados em acurácia que os outros dois outros classificadores.

O classificador de redes neurais obteve resultado competitivo com SVM e, provavelmente ajustando parâmetros dos dois classificadores poder-se-ia obter resultados ainda melhores. O mesmo vale para o Nayve Bayes em termos de obter melhores resultados, embora sua acurárcia não tenha sido competitiva em relação aos outros dois.

Em particular, o Nayve Bayes obteve o pior resultado, mas é importante lembrar que esse método é mais rápido, fácil de treinar e interpretar os resultados que redes neurais e SVM. Adaptar o Nayve Bayes de maneira incremental ou para novos dados é simples e rápido, já fazer isso para redes neurais pode não trazer bons resultados e talvez exigir mudanças na topologia da rede.
Em relação ao SVM, o Nayve Bayes assume independência entre as features, já o SVM, em termos simples, olha a interação entre essas features até um certo grau. Apesar disso, o consumo de memória e tempo de execução do SVM pode crescer muito em relação ao Nayve Bayes.